README.md
STL.html

Added Reverse Algorithm in Readme.Md file

---

algorithm.md

added all_of() & any_of() functions with link to run code as well

added  2 functions

---

algorithm.md

added 2 new functions

---

algorithm.md

This PR is in response to issue #36 , Add Run Code Links in existing code snippets.  
I ran the sample code provided under the Generate algorithm in Rextester, created a permanent link and added this as "Run Code" in the Generate Section.
Thanks!

Generate Run Code link added

---

CONTRIBUTING.md
README.md
algorithm.md

Made some changes to the README and CONTRIBUTING guide. Added inline links to some GitHub Help pages to make the documents more robust and user-friendly. Hopefully the changes are appreciated. Thanks! ☺️

README and CONTRIBUTING update

---

vector.md
vector/erase.cpp

Add examples on how to use the erase functions for vector containers. I also added an example on how to remove a specific value from the vector using the algorithm library.
This is my first ever pull request, so any advices are welcome.

vector::erase

---

algorithm.md

This pull request references issue #36. I added links to running code examples of binary_search and reverse. I also fixed the binary_search code to match the code style guidelines, and fixed a typo in the reverse example code.

Add run code links to binary_search and reverse

---

queue.md
queue/back.cpp
queue/front.cpp

This PR is for #31 and #36. I have completed front.cpp and back.cpp for queue. I also added examples and run links for these functions in queues.md.

Add queue front back functions

---

vector.md

Added Run Code link for assign function

---

algorithm.md

This is my first time contributing so I'm not entirely sure I did everything right. I followed the directions in the contributing.md and added a run code link at the bottom of the count_if function in the algorithm.md file. I plan on changing the example to match the run code since the run code has std:: instead of using namespace std;

Updated algorithm.md with run code for count_if function

---

queue.md
queue/emplace.cpp
queue/empty.cpp
queue/size.cpp
queue/swap.cpp

#31 #36 
Added remaining functions in queues.md. Also added the examples and run code links for each function in their respective positions in queues.md.
Thank you!

Complete queue functions

---

algorithm.md

This change has a bit more changes since I got the hang of the process a little better. I changed the formatting of the links to match the algorithm run code at the bottom of the page. I changed the title of the count_if run code seeing as I labeled it wrong. I added Run Code for find, find_if, find_if_not, find_first_of and finally I changed all the code for those particular code to use std:: for uniformity. Hopefully this helps.

Algorithm.md Format fixes for uniformity and added Run Code to find, find_if, find_if_not, find_first_of

---

stack.md
stack/size.cpp

I created size.cpp in the stack folder to show how size() is used for stacks.

Create size.cpp to show how size() is used for stacks

---

vector/insert.cpp

Added vector::insert

---

algorithm.md

Added Run Code link to sort example in algorithm.md

Added Run Code link to Sort 

---

vector.md

Joj0z swap-vector-md

---

stack.md

Added Run Code links for push, pop, top, and empty.

Updated stack.md to include Run Code links

---

algorithm/for_each_n.md

Fix comment about result for for_each_n. #92

---

algorithm/for_each.md
algorithm/for_each_n.md

See #101 why i had to recreate the PR, sorry for the hassle :S 
Fixes the class names in for_each.md and for_each_n.md

Fix missing class names

---

algorithm/adjacent_find.md
list/assign.md
list/back.md
list/begin.md
list/cbegin.md
list/cend.md
list/clear.md
list/crbegin.md

#36 
I added some links for online compiler and added some 'std::',

Added some links to online compiler for running code

---

stack/README.md
stack/emplace.md

Just adding more to std::stack.

Add stack::emplace description

---

algorithm/accumulate.md
snippets/algorithm/accumulate.cpp

Added accumulate.md displaying the use of std::accumulate from algorithms library.

Added accumulate.md

---

algorithm/iota.md

Hello, this is Rahul Debnath. I'm starting out in open source contribution and this is one of my first contributions. Would love to get feedback, and please let me know if there are any issues in the pull request. :)

Added the iota project under Algorithms section

---

map/count.md
map/insert.md

Hi! This is my first contribution, please let me know if there's an issue with my code

Added count and insert to map directory

---

algorithm/copy.md
algorithm/copy_backward.md
algorithm/copy_if.md
algorithm/copy_n.md
snippets/algorithm/copy.cpp
snippets/algorithm/copy_backward.cpp
snippets/algorithm/copy_if.cpp
snippets/algorithm/copy_n.cpp

Added documentation and snippets for:
- copy
- copy_n
- copy_if
- copy_backward

Adding copy* algorithms

---

vector/resize.md

Added overview for vector::resize

add resize.md

---

algorithm/upper_bound.md

Added upper_bound method and attached code snippets for it's use with arrays,vectors and sets.

Added  upper_bound

---

algorithm/remove.md
algorithm/remove_copy.md
algorithm/remove_copy_if.md
algorithm/remove_if.md
algorithm/replace.md
algorithm/replace_copy.md
algorithm/replace_copy_if.md
algorithm/replace_if.md
snippets/algorithm/remove.cpp
snippets/algorithm/remove_copy.cpp
snippets/algorithm/remove_copy_if.cpp
snippets/algorithm/remove_if.cpp
snippets/algorithm/replace.cpp
snippets/algorithm/replace_copy.cpp
snippets/algorithm/replace_copy_if.cpp
snippets/algorithm/replace_if.cpp

Documenting more algorithms:
- remove
- remove_copy
- remove_copy_if
- remove_if
- replace_copy
- replace
- replace_if

Implementing more algorithms

---

set/size.md

@Bhupesh-V  This solves issue #120

std set.size()

---

unordered_map/erase.md
unordered_map/find.md
unordered_map/insert.md
unordered_map/size.md

New directory for unordered_map. I implemented 4 methods.

Added unordered_map

---

snippets/vector/pop_back.cpp
vector/pop_back.md

I added `pop_back.md` in `vector` and `pop_back.cpp` in `snippets/vector`.

Added 'pop_back()' in vectors

---

snippets/vector/capacity.cpp
vector/capacity.md

Added `capacity.cpp` in `snippets/vectors` and capacity.md in `vectors` to show how capacity() works in a vector.

Implemented capacity() in vectors

---

set/empty.md

added set.empty

---

snippets/vector/max_size.cpp
snippets/vector/reserve.cpp
vector/max_size.md
vector/reserve.md

I implemented `reserve` and `max_size` in vectors.

New vector functions

---

snippets/vector/shrink_to_fit.cpp
vector/shrink_to_fit.md

I implemented `shrink_to_fit` function in vectors.

Added shrink_to_fit in vectors

---

set/insert.md

added set.insert

---

list/swap.md
snippets/list/swap.cpp

I added `swap.cpp` in `../snippets/list` based on the exisiting `swap.md` file in `../list`.

Added swap() in list

---

snippets/vector/emplace.cpp
vector/emplace.md

I implemented `emplace()` function of vectors.

Added emplace() in vectors

---

vector/cbegin.md

Added cbegin of vector

---

set/contains.md

This function allows checking of the existence of a particular key in the
given set. The return value is boolean.
There is no support for this feature in ideone so I have removed the code from the markdown file. But there is no error.

Add function contains to set data structure

---

snippets/stack/swap.cpp
stack/swap.md

Added 'swap.md' at 'stack' and 'swap.cpp' at 'snippets/stack'

Added swap in stack

---

set/count.md
set/todo.txt

added count.md in set folder
remove count of todo.txt

Set add count 

---

vector/cend.md

Added cend of vector

---

snippets/vector/sort.cpp
vector/sort.md

Implementation of how to use sort() function in vectors

Added Sort() in vector

---

snippets/vector/cbegin.cpp

Hello, I wanted to contribute by creating an example for cbegin.cpp from the vector STL. 
If you would like any changes or modifications please let me know, 
Thank you.

Created cbegin.cpp for vector

---

set/lower_bound.md

Also removes redundancies with other open PRs along with ssh errors that I made previously on this branch.

Add set.lower_bound(x)

---

map/clear.md

Dear Sir, I have tried my best to explain the clear() function used in map C++ STL along with a code example for your repository : 30-seconds-of-cpp. Please accept my request and add this file to your in your map directory in the original branch.

std::map::clear() overview

---

vector/rbegin.md

Added rbegin of vector

---

algorithm/shuffle.md
set/shuffle.md
snippets/algorithm/shuffle.cpp

Adding shuffle () function that can arrange elements in range at random

Add shuffle() in array

---

snippets/algorithm/__gcd.cpp
snippets/algorithm/to_string.cpp
snippets/stack/push_&_pop.cpp

A simple function call to find the greatest common divisor (GCD) of two numbers.
Easy to call and find the required answer, minus the hassle of writing a GCD algorithm!

Created __gcd.cpp

---

algorithm/rotate.md
snippets/algorithm/rotate.cpp

I have added rotate() method finctionality in algorithms and wrote corresponding codes in as .cpp and .md files.

Added rotate() in algorithm

---

algorithm/random_shuffle.md

random_shuffle.md

---

algorithm/random_shuffle.md
snippets/algorithm/random_shuffle.cpp

added random_shuffle featur of STL

Added random_shuffle in Algorithm

---

snippets/vector/empty.cpp

Added a snippet of std::vector's empty function

added a snippet

---

list/emplace.md

Added emplace.md to the "list" directory.

Added emplace.md to list

---

snippets/list/emplace.cpp

Added emplace.cpp to snippets directory

Added emplace.cpp to snippets directory

---

snippets/vector/data.cpp
vector/data.md

data() in vector

---

map/empty.cpp
map/todo.txt

[Added] map empty function

---

snippets/vector/front.cpp

Displaying the use of front() function in a vector.

Add front.cpp

---

snippets/vector/back.cpp

Displaying the use of back() function in a vector.

Add back.cpp

---

snippets/vector/crbegin.cpp

Added code demonstrating the use of function crbegin() in vector

Add crbegin.cpp

---

snippets/map/clear.cpp

I have added clear.cpp for map. Please let me know if I need to make any changes or add anything.
Thank you.

made clear.cpp for map

---

snippets/map/emplace.cpp

Added snippet for emplace function in STL map

added emplace.cpp

---

snippets/vector/emplace_back.cpp
vector/emplace_back.md

add emplace_back() function for vector

---

set/rbegin.md
set/rend.md
set/todo.txt

If you like the work, let me collaborate with you :)

Added new functions in SET by Yadhukrishnan P

---

algorithm/equal_range.md

Adding extraneous [ char in equal_range

Adding extraneous [ char in equal_range

---

vector/empty.md
vector/front.md

Also fixed an issue with front example.

Add vector run code links

---

set/find.md

Corrected a typo
Made code more detailed
Added Ideone Code Run link

Fixed find() in set

---

set/find.md

Update wrong heading in find.md

---

snippets/vector/get_allocator.cpp

Added a snippet for the get_allocator function for vectors.

Added get_allocator snippet

---

snippets/algorithm/lexicographical_compare.cpp

Added an example code for lexicographical_compare in algorithm

Added snippet for lexicographical_compare in algorithm

---

.github/workflows/main.yml

I did not know on which which system you are running your program so i did it for my system ubuntu-18.04 due to which the shell command may be different on windows.

Automate running of update_readme.py

---

algorithm/reverse_copy.md

I added the implementation of the reverse_copy method for algorithm. (#452 )

Reverse_copy

---

unordered_map/README.md
unordered_map/count.md

Added method count for unorderedmap

Added method count for unorderedmap

---

list/max_size.md

max_size.md

---

snippets/list/max_size.cpp

max_size.cpp

---

algorithm/generate_n.md
snippets/algorithm/generate_n.md

Adding generate_n.md to both the <algorithm> and <snippets> directories of the project.

Adding algorithm::generate_n.md

---

.vscode/settings.json
priority_queue/README.md
priority_queue/pop.md
priority_queue/priority_queue.md
priority_queue/push.md
priority_queue/size.md
priority_queue/top.md

hey ping me up incase of any modifications or changes .

priority_queue addition to this repo

---

algorithm/README.md
algorithm/inner_product.md
snippets/algorithm/inner_product.cpp

I have added code under the `/snippets/algorithm` about how to use the inner_product(). Furthermore, I have written an explanation of how inner_product() works and how to use it under the `/algorithm` folder as markdown. #31

Showing the usage of inner_product()

---

snippets/algorithm/copy.cpp
snippets/algorithm/copy_backward.cpp
snippets/algorithm/copy_if.cpp
snippets/algorithm/copy_n.cpp
snippets/algorithm/includes.cpp
snippets/algorithm/merge.cpp
snippets/algorithm/nth_element.cpp
snippets/algorithm/remove.cpp
snippets/algorithm/remove_copy.cpp
snippets/algorithm/remove_copy_if.cpp
snippets/algorithm/remove_if.cpp
snippets/algorithm/replace.cpp
snippets/algorithm/replace_copy.cpp
snippets/algorithm/replace_copy_if.cpp
snippets/algorithm/replace_if.cpp
snippets/algorithm/rotate.cpp
snippets/algorithm/set_difference.cpp
snippets/algorithm/set_intersection.cpp
snippets/algorithm/set_union.cpp
snippets/algorithm/transform.cpp
snippets/algorithm/upper_bound.cpp

All updates in this pull request are fixing the opening braces in the snippets/algorithms directory. All main functions now have opening braces on the same line, as per the style guide.

Styling Cleanup - Braces in algorithm snippets

---

algorithm/find_end.md
snippets/algorithm/find_end.cpp

First contribution for find_end algorithm. Thanks for setting this up!

Algorithms: Add find_end markdown and snippet

---

algorithm/is_sorted_until.md

Added a new function under Algorithm library.

Added is_sorted_until.md

---

map/README.md
map/equal_range.md

Added the equal_range program in under map. Please let me know your suggestions as this is my first open source contribution.

Added equal_range in Map dir

---

algorithm/partition_copy.md
algorithm/unique_copy.md
snippets/algorithm/partition_copy.cpp
snippets/algorithm/unique_copy.cpp

Hi, I have added unique_copy and partition_copy with their respective examples

Added unique_copy and partition_copy algorithms

---

algorithm/stable_partition.md

This PR adds a description of **stable\_partition** in the **algorithm** library with also an example.
- algorithm/stable_partition.md has been created
- A description, an example code and a link to run this snippet has been included within this file

Added algorithm/stable_partition

---

set/crbegin.md
snippets/set/crbegin.cpp

This PR adds an example for std::set::crbegin().

Added crbegin example for std set

---

set/rbegin.md
snippets/set/rbegin.cpp

This PR makes changes to `rbegin.md` to conform to the `contributing.md` style guide. It also adds a corresponding `rbegin.cpp` code snippet.
- Remove `<bits/stdc++.h>` header and replace it with the correct `<set>` include.
- Update set to use list initialization rather than copying from a C-style array.
- Remove `using namespace std`.
- Print all elements in the set rather than a single element.
- Update run code example.
- Add code snippet.

Update set rbegin to match style guide

---

stack/swap.md

Run Code link shifted to next line

---

vector/data.md

Signed-off-by: destro-2698 <aakashgupta2698@gmail.com>
This PR...consists of adding run code links below the snippet for data.md in vector library.
Fixes #36
- added a link to Rextester compiler to have the option to try and run the code.

added run code link to data.md in vector library
